site_name: 恋爱记录
site_author: Matrix
site_url: https://github.com/L-N1988/open-channel

theme:
  name: material
  custom_dir: theme
  font: false
  icon:
    logo: material/heart
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - navigation.tabs

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search

repo_name: L-N1988/open-channel
repo_url: https://github.com/L-N1988/open-channel

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: "index.md"
  - 代办清单: "todos.md"
  - 照片墙: "photos.md"
  - 视频墙: "videos.md"
  - 纪念日历: "calendar.md"
